### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by EmanuelDellsen**
Change to travis file so that the tests work

### CODE REVIEW

**Comment by platisd** [comment]
Not sure what you guys are doing exactly with those weird removals

**Comment by EmanuelDellsen** [comment]
Just trying to figure out how to properly add the .travis.yml file to the
master branch and see that it works. Can't figure out any other way. And
each time it has failed I closed the pull request due to it failing.

**Comment by platisd** [comment]
The way of working should be:
1. Open a pull request
2. Keep pushing fixes until it works
3. When it works, (squash and) merge.

**Comment by EmanuelDellsen** [comment]
What is in the master works on both android studios on the computer and also on the phone as an app but the CI keeps providing errors. I will look more into it before I continue this pull request harassment..

**Comment by platisd** [comment]
On the CI logs, it fails because it cannot find the NewPing library:
> basicObstacleAvoidance:1:21: error: NewPing.h: No such file or directory

You will need to install it first.

**Comment by EmanuelDellsen** [comment]
" - arduino --install-library "NewPing" " should work as far as I understand?

**Comment by platisd** [comment]
`NewPing` can be installed via the Arduino IDE's library manager, so yes.

**Pull request closed without merging**
