### PR TITLE
Features/predetermined route

### PR DESCRIPTION
**Pull request by JonatanVaara**
I was probably in the wrong branch while doing these commits. But they still needs to be merged with dev.

### CODE REVIEW

**Comment by platisd** [comment]
Why to `dev` and not `master`? :scream:

**Comment by JonatanVaara** [comment]
Merging to master is something we don't do very often. 
So for these small commits, I'm just trying to follow our convention :)

**Comment by platisd** [comment]
Oh, why is that your convention though?

**Comment by JonatanVaara** [comment]
Someone should correct me if I'm wrong, but I believe we decided to do it since we're working in sprints. 
So that we can do a pull-request to the master-branch to signify the end of a sprint.

**Comment by platisd** [comment]
Aha I see. So kind of like a sprint release.
Well, since you're the only team working on the system that will work but once more start to get involved then you'd eventually run into problems. 

I'd suggest you move towards merging directly to master. Aside of the semantics, I don't see any particular value in having weekly releases. :+1:

**Pull request merged**
