### PR TITLE
Features/google maps

### LINKED ISSUE #73: Create Route with Polyline on Map
When the user touches a position on the map, a route to that position should be created and a polyline drawn on the map.

### PR DESCRIPTION
**Pull request by NiklasMoller**
## Description
Creating a route object and a polyline when user taps position at the map.
Converting the route to car instructions

## Related issues

Fixes #73 #38

### CODE REVIEW

**Comment by EmanuelDellsen** [comment]
@platisd We have a google API for our google-maps feature and this API is linked to a credit card which we do not want to be public, therefor we need to skip the building of a certain java class which needs this API to pass the build. How can this be done in the .travis.yml? Thank you in advance

**Comment by platisd** [comment]
Would it work to add them as environment variables and fetch them with code?
Then you can set them in your IDE/[gradle](https://stackoverflow.com/questions/34941043/how-do-i-set-an-environment-variable-in-android-studio-before-it-runs-my-gradle) as well as on [Travis](https://travis-ci.org/DIT112-V19/group-05/settings).

**Comment by NiklasMoller** [comment]
I tried that earlier but am to inexperienced to make it work. Our TA's encourage us to put in a .xml and use .gitignore.

**Comment by platisd** [comment]
A file-based solution that is not version controlled will only work for local builds. During the weekend I will try to set up an example application with TravisCI, that sets up some API keys (probably as properties) and reads them in an app.

**Comment by NiklasMoller** [comment]
@platisd Thanks, that would be much helpful 👍

**Comment by platisd** [comment]
Hi,
Please refer to the changes introduced in DIT112-V19/arduino-android-ci#1 and let me know if you have any questions.

**Pull request merged**
